### ISSUE TITLE
Find/Purchase a Bootstrap Theme 

### ISSUE THREAD

**Issue by pamtaro** [TechEdSpotlight/TechEdSpotlight#1]
https://wrapbootstrap.com

**Comment by pamtaro** [comment]
Picked https://wrapbootstrap.com/theme/restart-clean-minimal-business-WB0NPLR53
Seams to be the most polished for < $15 with enough variety for our needs.

**Comment by jmdembe** [comment]
That's a pretty clean layout right there!

**Comment by peterylai** [comment]
👍
