### ISSUE TITLE
Apply Purchased Bootstrap Theme

### ISSUE THREAD

**Issue by pamtaro** [TechEdSpotlight/TechEdSpotlight#2]
Apply the theme's styles/scripts and update the following to start:
- [ ] - Layout
- [ ] - Homepage
- [ ] - Login/registration
- [ ] - Story View

**Comment by peterylai** [comment]
so the theme we purchased is all written in LESS, but all of our stuff currently is SCSS. What do you want to do? Switch everything over to LESS?

**Comment by pamtaro** [comment]
There's very little styling we're attached to right now, so I wouldn't mind moving it to LESS or keeping it in SCSS. 

Generally, whenever I integrate a 3rd party theme I've just referenced the already compiled CSS (with maybe a few changes to the variables file for colors/fonts ) so that it can be pre-processed from any other language first and not have to be handled in the asset pipeline the same way. It's a personal preference just so there's a clear delineation between which styles are coming from a theme that we'll want to keep mostly the same for future upgrades and which styles are 'owned' by the app. We can still have it be a part of the Rails asset compilation and make everything LESS, as long as it's a part of the vendor assets so that any future customization beyond the variables are only handled in the app's own assets/stylesheets files.
